### ISSUE TITLE
本地包的方式引入项目报错

### ISSUE THREAD

**Issue by usernameisMan** [xxholly32/vue-general-components#1]
![image](https://user-images.githubusercontent.com/18171441/86334477-d5ad6300-bc7f-11ea-9de0-cd8010b812e2.png)
![image](https://user-images.githubusercontent.com/18171441/86334587-ffff2080-bc7f-11ea-8213-e5b8294c2f49.png)

我搞不懂为啥要去包里面找配置 .eslintrc.json

**Comment by usernameisMan** [comment]
是因为。。我把element-ui 一起打包照成的

**Comment by xxholly32** [comment]
有解决么？这个应该不用带element-ui的，这个只是做一个库。还是说你的项目需要引入el的部分组件？

**Comment by usernameisMan** [comment]
> 有解决么？这个应该不用带element-ui的，这个只是做一个库。还是说你的项目需要引入el的部分组件？

解决了

rollup.config.base.js 
```js
export default {
  input: 'src/index.js',
  external: [ 'element-ui' ],   <---------------- 改为外部的了
```
