### ISSUE TITLE
提议 rollup.config.base 配置增加一个 external

### ISSUE THREAD

**Issue by usernameisMan** [xxholly32/vue-general-components#2]
为什么我觉得要加入 `external: ['vue']`  因为如果使用引入了 ` vue.use`  等功能时候，在包在项目使用中会出现 [` Vue的两个实例` ](https://github.com/vuetifyjs/vuetify/discussions/4068) 问题

如果有必要的话
我可以 fork 发一个 PR 过来🤩嘻嘻

**Comment by xxholly32** [comment]
嗯嗯，这个确实疏忽了，应该是打包的时候加上的
